name: Test continue-on-error behavior

on:
  push:

jobs:
  matrix-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job: [1, 2, 3]

    continue-on-error: true

    steps:
      - name: Check Job
        run: echo "Running on Job ${{ matrix.job }}"
      
      - name: Fail or Sleep
        run: |
          if [ "${{ matrix.job }}" == "2" ]; then
            echo "Intentionally failing this job..."
            exit 1
          else
            echo "Waiting for 30 seconds to allow the fail job to run..."
            sleep 30
            echo "This job will succeed."
          fi
