name: test

on:
  push:

jobs:
  build:
    name:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    environment: ${{ github.ref_name == 'main' && 'production' || 'staging' }}

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: env check
      run: |
        echo ${{ github.ref_name }}
        echo ${{ vars.ENV }}