name: Test continue-on-error behavior

on:
  push:

jobs:
  set-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: |
          echo "matrix={\"job\": [1, 2, 3]}" >> $GITHUB_OUTPUT

  matrix-test:
    needs: set-matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false # これを false に設定することで、continue-on-error が正しく機能する
      matrix:
        job: ${{ fromJSON(needs.set-matrix.outputs.matrix).job }}

    continue-on-error: true # 1つの並列ジョブが失敗しても他のジョブはキャンセルされずに続行される

    steps:
      - name: Check Job
        run: echo "Running on Job ${{ matrix.job }}"
      
      - name: Fail or Sleep
        run: |
          if [ "${{ matrix.job }}" == "2" ]; then
            echo "Intentionally failing this job..."
            exit 1
          else
            echo "Waiting for 30 seconds to allow the fail job to run..."
            sleep 30
            echo "This job will succeed."
          fi
